default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
-   repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
    - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: local
    hooks:
      - id: flakehell
        name: flakehell
        entry: flakehell
        args: [lint]
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: [
          'flake8~=3.9.1',
          'flakehell~=0.9.0',
          'flake8-builtins~=1.5.3',
          'flake8-blind-except~=0.2.0',
          'flake8-logging-format~=0.6.0',
          'flake8-bugbear~=21.4.3',
          'flake8-annotations~=2.6.2',
          'flake8-docstrings~=1.6.0',
          'flake8-bandit~=2.1.2',
          'darglint~=1.8.0'
        ]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
        files: .py$
